repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      - id: ruff
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: codecov-config
        name: codecov-config-check
        description: Check if the codecov config file is valid
        files: ".github/.codecov.yml"
        entry: >
          sh -c "curl -V --keepalive-time 60 \\
                 --data-binary @.github/.codecov.yml \\
                 https://codecov.io/validate | grep Valid"
        language: system
        pass_filenames: false
