name: test

on:
  push: null

jobs:
  commit_msg:
    name: commit_msg
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Run commit message checks
        shell: bash -l {0}
        run: |
          git fetch
          currentbranch=`git branch | grep \* | cut -d ' ' -f2`
          for i in `git rev-list $currentbranch...origin/main`
          do
            echo $i
            gitmessage=`git cat-file commit "$i" | sed '1,/^$/d'`
            echo $gitmessage | .githooks/commit-msg
            echo $gitmessage
          done
