name: lint

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  call-workflow:
    uses: lsst/rubin_workflows/.github/workflows/lint.yaml@main
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
